name: Update data

on:
  schedule:
    - cron: 0 * * * *

jobs:
  update-data:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: update data
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: Updated ${{ env.date }}
          email: action@github.com
          name: GitHub Action
